# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import prefetch_pb2 as prefetch__pb2


class PrefetcherStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PrefetchData = channel.unary_unary(
                '/prefetch.Prefetcher/PrefetchData',
                request_serializer=prefetch__pb2.PrefetchRequest.SerializeToString,
                response_deserializer=prefetch__pb2.PrefetchReply.FromString,
                )


class PrefetcherServicer(object):
    """The greeting service definition.
    """

    def PrefetchData(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PrefetcherServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PrefetchData': grpc.unary_unary_rpc_method_handler(
                    servicer.PrefetchData,
                    request_deserializer=prefetch__pb2.PrefetchRequest.FromString,
                    response_serializer=prefetch__pb2.PrefetchReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'prefetch.Prefetcher', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Prefetcher(object):
    """The greeting service definition.
    """

    @staticmethod
    def PrefetchData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/prefetch.Prefetcher/PrefetchData',
            prefetch__pb2.PrefetchRequest.SerializeToString,
            prefetch__pb2.PrefetchReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
