# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: prefetch.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprefetch.proto\x12\x08prefetch\"<\n\x0bPrefetchMsg\x12\x11\n\tsubsys_id\x18\x01 \x01(\r\x12\r\n\x05ns_id\x18\x02 \x01(\r\x12\x0b\n\x03pba\x18\x03 \x01(\x04\"6\n\x0fPrefetchRequest\x12#\n\x04msgs\x18\x01 \x03(\x0b\x32\x15.prefetch.PrefetchMsg\"\x0f\n\rPrefetchReply2R\n\nPrefetcher\x12\x44\n\x0cPrefetchData\x12\x19.prefetch.PrefetchRequest\x1a\x17.prefetch.PrefetchReply\"\x00\x42\x32\n\x19io.grpc.examples.prefetchB\rPrefetchProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prefetch_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\031io.grpc.examples.prefetchB\rPrefetchProtoP\001\242\002\003HLW'
  _PREFETCHMSG._serialized_start=28
  _PREFETCHMSG._serialized_end=88
  _PREFETCHREQUEST._serialized_start=90
  _PREFETCHREQUEST._serialized_end=144
  _PREFETCHREPLY._serialized_start=146
  _PREFETCHREPLY._serialized_end=161
  _PREFETCHER._serialized_start=163
  _PREFETCHER._serialized_end=245
# @@protoc_insertion_point(module_scope)
